Claim Aware Ability
max-lt/nginx-jwt-module pull request #23
Opened 2022-01-30 13:25 UTC by aliprogrammer69

with this changes, module can grant claims

2022-02-01 12:20 UTC, max-lt commented
Hi, thanks for the PR, I will review it as soon as I can

2022-02-01 15:41 UTC, max-lt requested changes
Seems good, but there is some code style issues remaining.

2022-02-01 15:41 UTC, max-lt commented on README.md
> +        auth_jwt_claim claim_name $Variable;
lowercase Variable -> variable

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +
Why ?

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +  ngx_str_t key;              //Claim Name
Missing space

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +  ngx_int_t var_index;        // if claim value was variable var_index cotains variable index. if variable index not found = -1
Missing uppercase at the beginning of your sentence

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +  ngx_int_t var_index;        // if claim value was variable var_index cotains variable index. if variable index not found = -1
Use  NGX_CONF_UNSET instead of -1

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +      ngx_conf_set_auth_jwt_claim,//ngx_conf_set_keyval_slot,
Remove commented code "ngx_conf_set_keyval_slot"

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +      NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_HTTP_LOC_CONF|NGX_CONF_TAKE2,
You're using 4 spaces here, the project uses 2 spaces

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +      NULL},
Missing blank line after block

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +
Remove this

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +    ngx_log_error(NGX_LOG_WARN, r->connection->log, 0, "JWT: the jwt has expired [exp=%ld]", (long)exp);
Revert this

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +  if(conf->jwt_claims){
Missing space after "if"; Missign breakline after right parenthesis

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> -
Revert this; blank line after a block for this project

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +  conf->jwt_claims = !conf->jwt_claims ? prev->jwt_claims : conf->jwt_claims;
Use ngx_conf_merge_value

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +      claim_conf->var_index = -1;
Missing block

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +    claim_conf->key= value[1];
Missing space before =

2022-02-01 15:41 UTC, max-lt commented on src/ngx_http_auth_jwt_module.c
> +      unsigned char* claim_value;
I think that using `ngx_str_t *` should be simpler.

2022-02-01 16:15 UTC, aliprogrammer69 commented on src/ngx_http_auth_jwt_module.c
> +}
i can't understand what is the problem

2022-02-01 16:21 UTC, aliprogrammer69 commented on src/ngx_http_auth_jwt_module.c
> +      if(ngx_strncmp(claim,claim_value,(int)strlen(claim)) != 0){
because  claim is not ngx_str_t.

2022-03-10 12:14 UTC, max-lt commented
Hi, thank you for taking the time to make the changes.
I'll review it soon, but from what I saw there may be some limitations to this additional feature (tell me if I'm wrong) :  
consider the following JWT : 

```json
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true
}
```
so to check the suv param the config file will be 
```
auth_jwt_claim "sub" "1234567890";
```
but if I want to check to admin claim can I do 
```
auth_jwt_claim "admin" "true";
```
in other words : is the boolean parsed as string while comparing ? 

One last thing : can we compound the claims in the same block ? like
```
location /secured {
  auth_jwt_claim "sub" "1234567890";
  auth_jwt_claim "admin" "true";
}
```

2022-10-26 09:21 UTC, Mr-Markus commented
@max-lt is this no longer maintained or why is the PR still open?
I would like to use that claim feature, but my C skills are to less to review it.

2022-10-26 09:31 UTC, max-lt commented
I think that I will close it as it adds too much complexity to the existing code for an incomplete feature (I would expect this to work with arrays, booleans, numbers... but it only works for strings).
I would advise anyway to handle authorizations in your application, (for the moment) this module only handles authentications.

2022-10-26 09:33 UTC, aliprogrammer69 commented
@Mr-Markus the author (Max It)  asked me a question but i have forgotten to review and answer. cause i developed this feature a long time past, i have to review my codes again and then answer the "max-it". i'll review my codes and answer the question this weekend and i wish @max-lt accept and merge the PR

2022-10-26 09:38 UTC, Mr-Markus commented
Ah ok, I understand and agree with @max-lt that complexity is growing with this feature, but I also see reasons for implementing this. 

So @max-lt, do you think you would give it a chance or not? If not, @aliprogrammer69 I would merge changes in your repo into my fork :-)

Thanks for your replies

2022-10-26 09:44 UTC, aliprogrammer69 commented
adding new features is equal to putting more complexity into the code.  
@Mr-Markus be comfortable dude, do anything you want :-)

2022-10-27 08:31 UTC, max-lt commented
@Mr-Markus Yes of course, this is a very cool feature and it definitely have it's place here.

Here are some requirements :

## features 

### **must** have:

Simple check (on string):
```
location /secured {
  auth_jwt_claim "sub" "1234567890";
}
```

Compound check (on strings) that ensure **every** conditions is met:
```Compound check:
location /secured {
  auth_jwt_claim "sub" "1234567890";
  auth_jwt_claim "role" "admin";
}
```

### nice to have:

type casting for booleans:
```
location /secured {
  auth_jwt_claim "admin" "true::boolean";
}
```

type casting for numbers (i actually don't see any useful usage of this but why not):
```
location /secured {
  auth_jwt_claim "role" "5::number";
}
```

checks for array membership:
```
location /secured {
  # with `contains` keyword, directive would ensure that `roles` is an array
  auth_jwt_claim "roles" contains "manager";
}
```

## code seggregation 

Please move all of your additionnal code in a separate file, if this project have to grow it would be nice to be able to activate / deactivate additional feature :

```c
#include <jwt.h>
#include <jansson.h>

#define FEATURE_CLAIM
#ifdef FEATURE_CLAIM
  #include "featur_claim.h"
#endif

// ...

static ngx_command_t ngx_http_auth_jwt_commands[] = {
  // ...

#ifdef FEATURE_CLAIM
  { ngx_string("auth_jwt_claim"),  
    NGX_HTTP_MAIN_CONF|NGX_HTTP_SRV_CONF|NGX_HTTP_LOC_CONF|NGX_CONF_TAKE2,  
    ngx_conf_set_auth_jwt_claim,
    NGX_HTTP_LOC_CONF_OFFSET,  
    offsetof(ngx_http_auth_jwt_loc_conf_t, jwt_claims),
    NULL },
#endif

  ngx_null_command
};

// ...
```

2022-10-27 08:34 UTC, max-lt commented
@aliprogrammer69 actually I just reread your code and it's pretty cool as is, if you don't have time anymore for this feature I can take over from there.

2022-10-27 09:02 UTC, merged

2022-10-27 10:20 UTC, max-lt commented
Ok, for now I merged you branch in a development branch ([feature/grant-claims](https://github.com/max-lt/nginx-jwt-module/tree/feature/grant-claims)), I'll thoroughly review it before merging into master.

Your branch did not passed test suite: if `auth_jwt_claim` is not set the request is crashing, fixed it in [e3877fc](https://github.com/max-lt/nginx-jwt-module/commit/c9483dd81887c90382416071a8c7f1244d4b62a7#diff-4a419c3631706839f53d27f91b97460b04fde67e4c173f6c1bd173c59d12dceaL195-R195)  (`NGX_CONF_UNSET_PTR` is not nullish)

2022-11-01 12:42 UTC, max-lt commented
@Mr-Markus I juste released a new version (v3.2.0) that is able to perform additional verifications on JWTs claims and headers,

I finally did not used @aliprogrammer69 's solution but implemented something that looks more like [nginx solution](http://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html#auth_jwt_require).